### PR TITLE
Performance updates

### PR DESCRIPTION
**Pull request by VaiTon**
With this PR i want to improve region handling in terms of performance. (Related to #362)
That's what i did:
* Implemented an HashMap where every loaded chunk is in pair with the set of regions in the chunk.
* Replaced most of the calls to getRegionsByWorld with getRegionsInChunks
* Other minor improvement and fixes

### CODE REVIEW

**Comment by VaiTon** [comment]
@FabioZumbi12 bump

**Comment by FabioZumbi12** [comment]
I need to add this changes manually because a lot of changes on my local resources. Thanks for improvements and you can still adding what you want, when i update will be all included <3

**Comment by VaiTon** [comment]
Why did you close this? @FabioZumbi12

**Comment by Darkilen** [comment]
@VaiTon Check his last comment, he will add this change manually in his local files before push it to github

**Comment by VaiTon** [comment]
@Darkilen yeah i understood but no reason to close this

**Comment by FabioZumbi12** [comment]
To you dont add more commits in this PR, and yes in a new one with no conflicts! You changes is in all line and not only on specific changes, breaking tje PR and causing conflicts.

**Comment by VaiTon** [comment]
Should I create a new PR? @FabioZumbi12

**Comment by FabioZumbi12** [comment]
Yeah, please!!

**Pull request closed without merging**
